### PR TITLE
fix: added missing highlight param

### PR DESCRIPTION
**Pull request by dane-stevens**

### CODE REVIEW

**Comment by danitseitlin** [comment]
@dane-stevens Is this ready?

**Comment by dane-stevens** [comment]
@danitseitlin ready 👍🏻

**Comment by dane-stevens** [comment]
@danitseitlin sorry, I'll let you know next time

**Comment by danitseitlin** [comment]
@dane-stevens just request my review next time

**Review by danitseitlin — APPROVED** [review]
Thanks!

**Pull request merged**
